### ISSUE TITLE
Double-voting in SnapshotERC20Guild

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxdao-contracts#151]
<img width="717" alt="Screenshot 2022-06-13 at 12 25 05" src="https://user-images.githubusercontent.com/39137239/173343578-e6a932a4-ef17-493c-a9b7-c1af460bc515.png">

**Comment by AugustoL** [comment]
fixed on #198

**Comment by rossneilson** [comment]
We did not address this and remains an open critical issue

![Screenshot 2022-08-30 at 09 53 49](https://user-images.githubusercontent.com/39137239/187394069-9a3b77f4-c375-4148-9170-cd2fdc242ac0.jpg)
