### ISSUE TITLE
Voting Tally Does Not Count the Zero Action

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxdao-contracts#154]
<img width="724" alt="Screenshot 2022-06-13 at 12 27 29" src="https://user-images.githubusercontent.com/39137239/173343916-83e70762-1ff1-4e58-b6a2-e271ff568d29.png">

**Comment by AugustoL** [comment]
We want to make action 0 votable, this means that a user can say I vote for action zero, and the voting power in the action zero for that user would increase.

So if a user already voted for action 0 it cant vote again and change their vote.
