### ISSUE TITLE
Voting Tally Results in Unexpected Winner

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxdao-contracts#166]
<img width="715" alt="Screenshot 2022-06-13 at 12 32 56" src="https://user-images.githubusercontent.com/39137239/173344754-73e8a50c-83c8-4e96-8470-c0b93f1aea0c.png">

**Comment by AugustoL** [comment]
I would suggest add a condition check that in case the amount of votes of the winning action is equal to other action set the winningAction to 0, this would reject the proposal execution and do nothing in case of a tie.
