### ISSUE TITLE
n-option (yes/no, or more than 2 option) support in a class beween guilds and erc20guild?

### ISSUE THREAD

**Issue by kermit4** [DXgovernance/dxdao-contracts#21]
Should there be a class inheriting erc20guild that supports multiple options that guilds would then inherit, rather than duplicating the code in each guild that wants to?

@kadenzipfel

I'd tag geronimo if I knew his github.

**Comment by KadenZipfel** [comment]
Sounds to me like the best way to do it, but certain guilds might have needs specific to the project so maybe not in all circumstances
