### ISSUE TITLE
Comment purposeful ignoring of best practice

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxdao-contracts#72]
This is not to fix anything, ONLY to add a comment to prevent a future "fix" that would break things
<img width="539" alt="Screenshot 2022-02-28 at 16 21 16" src="https://user-images.githubusercontent.com/39137239/156080980-a21bf4fe-04e8-4695-8cbd-955a19e90fa9.png">

**Comment by AugustoL** [comment]
https://github.com/DXgovernance/dxdao-contracts/blob/d408539cb560a0675e6abb4726305c75e92d34a8/contracts/dxvote/DXDVotingMachine.sol#L561
