### ISSUE TITLE
Refund for voters not guaranteed - Will fix?

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxdao-contracts#97]
This issue identified in the audit relates to the dao running out of funds for a refund. The fix for this is a little involved and we could potentially look at just warning the user on the UI if it is out of funds.

@AugustoL what are your thoughts on fixing this?

<img width="945" alt="Screenshot 2022-03-28 at 09 46 40" src="https://user-images.githubusercontent.com/39137239/160361157-a9a33503-f678-42e8-be6e-ce8a5186deb4.png">

**Comment by AugustoL** [comment]
The refund will only happen if tehre is enough founds, if there is not enough funds for refund the vote would be processed anyways.

We will show a warning to the user that the refund balance is running low and he might not received the vote refund if he votes.

**Comment by rossneilson** [comment]
Sounds like a good solution, closing smart contract issue now and we can follow up in the UI
